### ISSUE TITLE
demo_sdf_

### ISSUE THREAD

**Issue by albertotono** [marian42/shapegan#17]
![Screenshot from 2021-10-07 14-55-13](https://user-images.githubusercontent.com/11828200/136468339-fc0c66e5-07b9-42f1-b51d-e7300699a007.png)

I am running the demo and I am getting an empty view. 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/alberto/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/alberto/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alberto/Documents/shapegan/rendering/__init__.py", line 299, in _run
    self._render()
  File "/home/alberto/Documents/shapegan/rendering/__init__.py", line 230, in _render
    light_vp_matrix = get_camera_transform(6, self.rotation[0], 50, project=True)
  File "/home/alberto/Documents/shapegan/rendering/math.py", line 20, in get_camera_transform
    camera_transform = np.matmul(camera_transform, get_rotation_matrix(rotation_x, axis='x'))
  File "/home/alberto/Documents/shapegan/rendering/math.py", line 14, in get_rotation_matrix
    matrix[:3, :3] = rotation.as_dcm()
AttributeError: 'scipy.spatial.transform.rotation.Rotation' object has no attribute 'as_dcm'
```

**Comment by albertotono** [comment]
solution pip install scipy==1.5.2
